### ISSUE TITLE
Unwanted gap / border / margin around dock

### ISSUE THREAD

**Issue by adatum** [micheleg/dash-to-dock#1440]
On Fedora 34 (Gnome Shell 40) with dash-to-dock version 69 (thanks, at least it's working now!) there is a gap / border / margin around the dock so that it is not flush with the side edge of the screen. A similar margin exists for window distances to cause the auto-hide feature to activate. 

Can this margin be reduced to zero? I did not find a setting which achieves this. 

I find it much easier to move the cursor to the very edge of the screen to click on launcher icons instead of having to center more careful on the icon.

![dash-to-dock-border](https://user-images.githubusercontent.com/9773655/117556905-d2bb9580-b03b-11eb-85e6-01ea497acc08.png)

**Comment by cjkr** [comment]
I have a similar problem. In my case, the margin is much more pronounced. Where in the code is this value set? I can manually change it while awaiting a possible permanent fix.

![Screenshot from 2021-08-28 23-39-13](https://user-images.githubusercontent.com/7858684/131230534-e4e4fdb3-123b-4927-b04c-5c41bba45b73.png)

**Comment by macgeneral** [comment]
As a workaround you can edit the following file (the location is valid for a global install in Manjaro):
```shell
user@pc:~$ sudo vim /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css
```

```css
line 4:
#dashtodockContainer.bottom #dash {
    [..]
    padding-bottom: 0px;
    [..]
}
```

and to get rid of the gap completely:
```css
line 19:
#dashtodockContainer.bottom.shrink #dash .dash-background {
    margin-bottom: 0px;
    [..]
}
```

Then simply open the Gnome Shell Extensions app and disable and enable Dash to Dock again.
