### ISSUE TITLE
border around dock

### ISSUE THREAD

**Issue by SilverMarcs** [micheleg/dash-to-dock#1455]
Not an issue but dont know where else to ask.
How do i add a border around the dash and how do I set the color of that border? 
I go to the stylesheet.css and?

**Comment by micheleg** [comment]
If you are up to tweak the css yourself, someting like 

```css
#dashtodockContainer .dash-background {
     border: 1px solid orange !important;
}
```
should do
