### ISSUE TITLE
Dock does not follow border styles when opacity is dynamic

### ISSUE THREAD

**Issue by CiberTurtle** [micheleg/dash-to-dock#1762]
The css code I'm using:
```css
.dash-background {
  background: darkblue !important; // Works fine
  border: 1px solid red !important; // Fades away then never comes back
}
```

Everything works as expected when opacity is set to fixed or default.
