### ISSUE TITLE
Tooltip moves to other monitor after dash auto-hide

### ISSUE THREAD

**Issue by johnnyasantoss** [micheleg/dash-to-dock#1763]
When right-clicking an item in the dash on the secondary monitor, the tooltip goes to the primary monitor, without acking the click on it.

Video:

https://user-images.githubusercontent.com/14189387/174118890-6deb3510-f80a-4a01-90de-8096145336ab.mp4

Running on Manjaro with 2 monitors
```
System:
  Host: thinkpad Kernel: 5.15.46-1-MANJARO arch: x86_64 bits: 64
    compiler: gcc v: 12.1.0 Desktop: GNOME v: 42.2 tk: GTK v: 3.24.34
    wm: gnome-shell dm: GDM v: 42.0 Distro: Manjaro Linux base: Arch Linux
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    vendor: Lenovo driver: amdgpu v: kernel arch: GCN 5 pcie: speed: 8 GT/s
    lanes: 16 ports: active: DP-3,eDP-1
    empty: DP-1, DP-2, DP-4, DP-5, HDMI-A-1 bus-ID: 06:00.0
    chip-ID: 1002:15d8 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.2
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: modesetting,radeon alternate: fbdev,vesa gpu: amdgpu
    display-ID: :1 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96 s-size: 1016x285mm (40.00x11.22")
    s-diag: 1055mm (41.54")
  Monitor-1: DP-3 mapped: DisplayPort-2 pos: right model: TGT-MN24ALTO1
    res: 1920x1080 dpi: 94 size: 520x320mm (20.47x12.6") diag: 611mm (24")
    modes: max: 1920x1080 min: 640x350
  Monitor-2: eDP-1 mapped: eDP pos: primary,left model: LG Display 0x05fa
    res: 1920x1080 hz: 60 dpi: 158 size: 309x174mm (12.17x6.85")
    diag: 355mm (14") modes: max: 1920x1080 min: 640x480
  OpenGL: renderer: AMD Radeon Vega 10 Graphics (raven LLVM 13.0.1 DRM 3.42
  5.15.46-1-MANJARO)
    v: 4.6 Mesa 22.1.1 direct render: Yes
```
