### ISSUE TITLE
Change margin of dock

### ISSUE THREAD

**Issue by andreacocci95** [micheleg/dash-to-dock#1957]
Hi, I would change the vertically size of margin of the dock to 0px.

I added on my stylesheet.css on .local/share/gnome-extensions/dash-to-dock this:
```css
# dashtodockContainer.bottom #dash .dash-background {
	margin-bottom: 0px !important;
	margin-top: 0px !important;
}
```

But the result is always the same (also after enable and disable the extension):
![image](https://user-images.githubusercontent.com/22175753/222899434-20905606-15a4-49a2-824b-fba0cd87d4dd.png)

If can be useful, I'm on Fedora 37 (Gnome 43.3).

Can you help me?
Thanks a lot!

**Comment by 3v1n0** [comment]
Do you use a custom theme?

Also there are other cases involving it, I'd suggest to edit the stylesheet scss file though and compile it in order not to forget things

**Comment by andreacocci95** [comment]
No, I'm not using custom theme. I'm pretty sure that with the CSS I posted, until some times ago, the dock are positioned right (without the margin at the bottom) or, however, it response on CSS changing.

**Comment by andreacocci95** [comment]
I solved myself the issue.

Modify the file in /home/<user>/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css

```css
#dashtodockContainer.bottom.shrink #dash .dash-background {
	margin: 0 !important; /* add !important */
    [...]
}

#dashtodockContainer.bottom.shrink #dash .dash-item-container .app-well-app,
#dashtodockContainer.bottom.shrink #dash .dash-item-container .show-apps {
    padding-bottom: 4px; /* Change from 7px to 4px */
    [...]
}
```

Save and disable and re-enable the addon. The result will be this:
